articles/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('', article, name='article'),  
    path('<int:id>/',article_detail, name='article_detail'),
    path('delete/<int:id>/',article_delete, name='article_delete'),
    path('edit/<int:id>/', edit_article, name='edit_article'),

    path('category/', category, name='category'),  
    path('category/<int:id>',category_detail, name='category_detail'),
    path('category/delete/<int:id>',category_delete, name='category_delete'),

    path('tag/', tag, name='tag'),  
    path('tag/<int:id>',tag_detail, name='tag_detail'),
    path('tag/delete/<int:id>',tag_delete, name='tag_delete'),

 
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news_portal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
#from django.urls import path
from django.urls import path, include
from website.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', welcome, name='home'),  
    path('signup', signup, name='signup'),     
    path('articles/', include('articles.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#The urls provided by this are
#accounts/login/ [name='login']
#accounts/logout/ [name='logout']
#accounts/password_change/ [name='password_change']
#accounts/password_change/done/ [name='password_change_done']
#accounts/password_reset/ [name='password_reset']
#accounts/password_reset/done/ [name='password_reset_done']
#accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
#accounts/reset/done/ [name='password_reset_complete']

articles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import UniqueConstraint


class Category(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        constraints = [
            UniqueConstraint(fields=['name', 'parent'], name='unique_name_within_parent')
        ]


class Tag(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Article(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='authored_articles')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    views = models.IntegerField(default=0)
    likes = models.ManyToManyField(User, related_name='%(app_label)s_%(class)s_likes', blank=True)
    image = models.ImageField(upload_to='article_images/', blank=True)

    def __str__(self):
        return self.title

    def total_likes(self):
        return self.likes.count()


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.author.username}\'s comment on {self.article.title}'


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='likes')
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    liked_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} liked {self.article.title}'


class View(models.Model):       
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    count = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.article}'


articles/forms.py
from django.forms import ModelForm, Textarea
from .models import *

class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = '__all__'


class TagForm(ModelForm):
    class Meta:
        model = Tag
        fields = '__all__'

class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = '__all__'

articles/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import *

#article
def article(request):
    if request.method== "POST":
        form = ArticleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')

    else:
        form= ArticleForm()
    return render(request, 'articles/create.html', {'form':form})

def edit_article(request, id):
    article = get_object_or_404(Article, pk=id)
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            form.save()
            return redirect('article_detail', id=article.id)
    else:
        form = ArticleForm(instance=article)
    return render(request, 'articles/create.html', {'form': form})

'''
def article_detail(request, id):
    articles = Article.objects.all()
    article = get_object_or_404(Article, pk=id)
    category= Category.objects.all() 
    view, created = View.objects.get_or_create(article=article)
    view.count += 1   
    view.save()
    return render(request, "articles/common.html", {'article': article, 'view_count': view.count,"categories":category,"articles":articles})
'''

from django.shortcuts import render, get_object_or_404
from .models import Article, Category, View

def article_detail(request, id):
    # Retrieve the requested article
    article = get_object_or_404(Article, pk=id)
    
    # Increment view count
    view, created = View.objects.get_or_create(article=article)
    view.count += 1   
    view.save()
    
    # Retrieve all articles
    articles = Article.objects.all()
    
    # Retrieve all categories
    categories = Category.objects.all()
    
    # Filter related news based on category of the current article
    related_news = Article.objects.filter(category=article.category).exclude(id=article.id)[:3]
    
    # Render the article detail page with relevant data
    return render(request, "articles/article_detail.html", {
        'article': article,
        'view_count': view.count,
        'categories': categories,
        'articles': articles,
        'related_news': related_news  # Pass related news to the template
    })


def article_delete(request, id):    
    data = get_object_or_404(Article, pk=id)
    data.delete()
    return redirect("/")

#category
def category(request):
    if request.method== "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form= CategoryForm()
    return render(request, 'articles/create.html', {'form':form})

def category_detail(request,id):
    data = get_object_or_404(Category, pk=id)
    return render(request, "articles/article_detail.html", {'data':data})

def category_delete(request, id):    
    data = get_object_or_404(Category, pk=id)
    data.delete()
    return redirect("/")

#Tag
def tag(request):
    if request.method== "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')

    else:
        form= TagForm()
    return render(request, 'articles/create.html', {'form':form})

def tag_detail(request,id):
    data = get_object_or_404(Tag, pk=id)
    return render(request, "articles/article_detail.html", {'data':data})

def tag_delete(request, id):    
    data = get_object_or_404(Tag, pk=id)
    data.delete()
    return redirect("/")





articles/templates/articles/article_detail.html
{% extends "website/base.html" %}

{% block title %}Article Detail{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-8 offset-md-2">
        <div class="card">
            {% if article.image %}
            <img src="{{ article.image.url }}" class="card-img-top mt-3" alt="Article Image">
            {% endif %}
            <div class="card-body">
                <h4 class="card-title"> {{ article.title }}</h4> 
                <i class="fa fa-eye"></i>{{ view_count }} 
                
                
                    <i class="fa fa-folder"></i>{{ article.category }}
                

                
                <p class="card-text">{{ article.content }}</p>
            </div>
            <div class="card-footer bg-light">
                <div class="row">


                    <div class="col-md-4">
                        <i class="fa fa-user"></i>{{ article.author }}
                    </div>
                    
                    <div class="col-md-4">
                        <i class="fa fa-tags"></i> Tags:
                        {% for tag in article.tags.all %}
                            <span class="badge badge-primary">{{ tag.name }}</span>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Related News Section -->
<div class="row mt-3">
    <div class="col-md-8 offset-md-2">
        <div class="related-news">
            <h3>Related News</h3>
            <ul>
                {% for related_article in related_news %}
                    <li><a href="{{ related_article.get_absolute_url }}">{{ related_article.title }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

<!-- Facebook Comment Plugin -->
<div class="row mt-3">
    <div class="col-md-8 offset-md-2">
        <div class="fb-comments" 
             data-href="{{ request.build_absolute_uri }}" 
             data-width="100%" 
             data-numposts="5">
        </div>
    </div>
</div>

<!-- Facebook Like Button Plugin -->
<div class="row mt-3">
    <div class="col-md-8 offset-md-2">
        <div class="fb-like" 
             data-href="{{ request.build_absolute_uri }}" 
             data-width="" 
             data-layout="standard" 
             data-action="like" 
             data-size="small" 
             data-share="true">
        </div>
    </div>
</div>

<!-- Include Facebook SDK -->
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v10.0"></script>
{% endblock %}

articles/templates/articles/commonn.html
{% extends "website/base.html" %}

{% block title %}Article Detail{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-8 offset-md-2">
        <div class="card">
            {% if article.image %}
            <img src="{{ article.image.url }}" class="card-img-top mt-3" alt="Article Image">
            {% endif %}
            <div class="card-body">
                <h4 class="card-title"> {{ article.title }}</h4> 
                <i class="fa fa-eye"></i>{{ view_count }} 
                
                
                    <i class="fa fa-folder"></i>{{ article.category }}
                

                
                <p class="card-text">{{ article.content }}</p>
            </div>
            <div class="card-footer bg-light">
                <div class="row">


                    <div class="col-md-4">
                        <i class="fa fa-user"></i>{{ article.author }}
                    </div>
                    
                    <div class="col-md-4">
                        <i class="fa fa-tags"></i> Tags:
                        {% for tag in article.tags.all %}
                            <span class="badge badge-primary">{{ tag.name }}</span>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Related News Section -->
<div class="row mt-3">
    <div class="col-md-8 offset-md-2">
        <div class="related-news">
            <h3>Related News</h3>
            <ul>
                {% for related_article in related_news %}
                    <li><a href="{{ related_article.get_absolute_url }}">{{ related_article.title }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

<!-- Facebook Comment Plugin -->
<div class="row mt-3">
    <div class="col-md-8 offset-md-2">
        <div class="fb-comments" 
             data-href="{{ request.build_absolute_uri }}" 
             data-width="100%" 
             data-numposts="5">
        </div>
    </div>
</div>

<!-- Facebook Like Button Plugin -->
<div class="row mt-3">
    <div class="col-md-8 offset-md-2">
        <div class="fb-like" 
             data-href="{{ request.build_absolute_uri }}" 
             data-width="" 
             data-layout="standard" 
             data-action="like" 
             data-size="small" 
             data-share="true">
        </div>
    </div>
</div>

<!-- Include Facebook SDK -->
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v10.0"></script>
{% endblock %}

articles/templates/articles/create.html
{% extends "website/base.html" %}
{% block title %}Create Post {% endblock %}
{% block content %}
<h2>Create a Post</h2>
<form method="post">
    <table>
        {{ form }}
    </table>
    {% csrf_token %}
    <button type="submit">Create</button>
</form>
{% endblock %}

articles/templates/articles/home.html
{% extends "website/base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <h1>Welcome to News Portal</h1>
        {% for category in categories %}
            <h2>{{ category.name }}</h2>
            <div class="row">
                <div class="col-md-12" style="overflow-x: auto;">
                    <div class="d-flex flex-row">
                        {% for article in category.article_set.all %}
                            <div class="col-md-4">
                                <div class="card mb-4 shadow-sm">
                                    <div class="position-relative"> <!-- Add position relative for absolute positioning -->
                                        {% if article.image %}
                                        <img src="{{ article.image.url }}" class="card-img-top" alt="img">
                                        {% endif %}
                                        <div class="card-body">
                                            <a href="{% url 'article_detail' article.id%}" ><h5 class="card-title">{{ article.title }}</h5></a>
                                            <p class="card-text">{{ article.content|truncatewords_html:20 }}</p> <!-- Limiting to 20 words -->
                                            <div class="d-flex justify-content-between align-items-center">
                                                <div class="btn-group">
                                                    <a href="{% url 'article_detail' article.id%}" class="btn btn-sm btn-outline-secondary">View</a>
                                                    <a href="{% url 'edit_article' article.id %}" class="btn btn-sm btn-outline-secondary">Edit</a>
                                                </div>
                                                <small class="text-muted">{{ article.created_at }}</small>
                                            </div>
                                        </div>
                                        <!-- Add triangular arrow -->
                                        <div class="arrow-right-middle"></div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

articles/templates/articles/search_results.html
searched_results